/**
 * Auto-generated types and API for Convex functions.
 * This file is typically generated by `npx convex dev`.
 * For this plan, we're creating a minimal version to enable TypeScript compilation.
 * Run `npx convex dev` to regenerate this file with complete types.
 */

import type { FunctionReference } from 'convex/server';

// Document types based on schema
export type Document = {
  _id: any;
  _creationTime: number;
};

export type FormTemplate = Document & {
  name: string;
  version: number;
  orgId: string;
  published: boolean;
  fields: any[];
  createdBy: string;
  publishedAt?: number;
  createdAt: number;
  updatedAt: number;
};

// API type references
export type API = {
  formTemplates: {
    listTemplates: FunctionReference<'query', '_internal', any, any[]>;
    getTemplate: FunctionReference<'query', '_internal', any, any>;
    listPublishedTemplates: FunctionReference<'query', '_internal', any, any[]>;
    createTemplate: FunctionReference<'mutation', '_internal', any, any>;
    updateTemplate: FunctionReference<'mutation', '_internal', any, any>;
    publishTemplate: FunctionReference<'mutation', '_internal', any, any>;
    unpublishTemplate: FunctionReference<'mutation', '_internal', any, any>;
    deleteTemplate: FunctionReference<'mutation', '_internal', any, any>;
  };
  voice: {
    transcribeAudio: FunctionReference<'mutation', '_internal', any, { text: string }>;
  };
};

// Create the api object with proper structure for Convex
export const api: API = {
  formTemplates: {
    listTemplates: 'formTemplates:listTemplates' as any,
    getTemplate: 'formTemplates:getTemplate' as any,
    listPublishedTemplates: 'formTemplates:listPublishedTemplates' as any,
    createTemplate: 'formTemplates:createTemplate' as any,
    updateTemplate: 'formTemplates:updateTemplate' as any,
    publishTemplate: 'formTemplates:publishTemplate' as any,
    unpublishTemplate: 'formTemplates:unpublishTemplate' as any,
    deleteTemplate: 'formTemplates:deleteTemplate' as any,
  },
  voice: {
    transcribeAudio: 'voice:transcribeAudio' as any,
  },
};
