/**
 * Type definitions for Convex server module.
 * This file is auto-generated by `npx convex dev`.
 */

import type { DataModel } from './dataModel';

declare module './_generated/server' {
  interface Env {
    dataModel: DataModel;
  }
}
